# hercules/tasks/deploy.yml

- name: download hercules rpm from git
  get_url: url={{ hercules_git_url }}/archive/{{ hercules_git_release }}.rpm dest={{ hercules_tmp_path }}/hercules-{{ hercules_git_release }}.rpm sha256sum={{ hercules_git_release_sha256sum }}
  ignore_errors: True 
  register: hercules_git_rpm

# If a RPM could not be obtained, build from source instead  
- include: package.yml
  when: hercules_git_rpm|failed
  tags: package
  
- name: install the hercules rpm
  yum: name={{ hercules_tmp_path }}/hercules-{{ hercules_git_release }}.rpm state=present
  